In [1]:
import datetime
from pyvalem.formula import Formula
from pyvalem.stateful_species import StatefulSpecies
from django.shortcuts import render
from django.http import Http404, StreamingHttpResponse, HttpResponse
from django.views.generic import View
# from models import Linelist, IDMolecule
# from filters import TransFilter
# from chem.models import Molecule, Isotopologue
import csv
import pandas as pd

In [2]:
def molecules(request):
    molecules_colnames = ['molid', 'molecule', 'molhtml', 'moltag', 'molname', 'molmass']
    molecule_df = pd.read_csv('~/ExoMolHR-web/res/molecules.csv', header=0, names=molecules_colnames)
    context = {
        'columns': molecule_df.columns, 
        'rows': molecule_df.to_dict('records')}   
    return render(request, 'calculate/molecules.html', context)

In [3]:
mol_columns = ['molid', 'molecule', 'molhtml', 'moltag', 'molname', 'molmass']
data = pd.read_csv('~/ExoMolHR-web/res/molecules.csv', header=0, names=mol_columns)
data

,molid,molecule,molhtml,moltag,molname,molmass
0,1,AlCl,AlCl,alcl,Aluminum monochloride,62.431538
1,2,AlH,AlH,alh,Aluminum hydride,27.989538
2,3,AlO,AlO,alo,Aluminum monoxide,42.980538
3,4,C2,C<sub>2</sub>,c2,Dicarbon,24.022000
4,5,C2H2,C<sub>2</sub>H<sub>2</sub>,c2h2,Acetylene,26.038000
5,6,CaH,CaH,cah,Calcium monohydride,41.086000
6,7,CN,CN,cn,Cyano radical,26.018000
7,8,CO2,CO<sub>2</sub>,co2,Carbon dioxide,44.009000
8,9,H2CO,H<sub>2</sub>CO,h2co,Formaldehyde,30.026000
9,10,H2O,H<sub>2</sub>O,h2o,Water,18.015000
10,11,H2S,H<sub>2</sub>S,h2s,Hydrogen sulfide,34.076000
11,12,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000
12,13,H3O+,H<sub>3</sub>O<sup>+</sup>,h3o+,Hydronium cation,19.023000
13,14,LiOH,LiOH,lioh,Lithium hydroxide,23.947000
14,15,MgH,MgH,mgh,Magnesium monohydride,25.313000
15,16,NH,NH,nh,Imidogen,15.015000
16,17,NH3,NH<sub>3</sub>,nh3,Ammonia,17.031000
17,18,NO,NO,no,Nitric oxide,30.006000
18,19,SiN,SiN,sin,Silicon nitride,42.092000
19,20,SiO,SiO,sio,Silicon monoxide,44.084000
20,21,SO,SO,so,Sulfur monoxide,48.059000
21,22,SO2,SO<sub>2</sub>,so2,Sulfur dioxide,64.058000
22,23,TiO,TiO,tio,Titanium oxide,63.866000
23,24,YO,YO,yo,Yttrium monoxide,104.904840
24,25,ZrO,ZrO,zro,Zirconium oxide,107.223000

In [4]:
data['molecule'][0]

'AlCl'

In [5]:
# sub_map = str.maketrans('0123456789', '₀₁₂₃₄₅₆₇₈₉')
# sup_map = str.maketrans('+-', '⁺⁻')
# data['Molecule'] = [formula.translate(sub_map).translate(sup_map) for formula in data['Molecule'].values]
# data

In [6]:
data.to_dict('records')

[{'molid': 1,
  'molecule': 'AlCl',
  'molhtml': 'AlCl',
  'moltag': 'alcl',
  'molname': 'Aluminum monochloride',
  'molmass': 62.431538},
 {'molid': 2,
  'molecule': 'AlH',
  'molhtml': 'AlH',
  'moltag': 'alh',
  'molname': 'Aluminum hydride',
  'molmass': 27.989538},
 {'molid': 3,
  'molecule': 'AlO',
  'molhtml': 'AlO',
  'moltag': 'alo',
  'molname': 'Aluminum monoxide',
  'molmass': 42.980538},
 {'molid': 4,
  'molecule': 'C2',
  'molhtml': 'C<sub>2</sub>',
  'moltag': 'c2',
  'molname': 'Dicarbon',
  'molmass': 24.022},
 {'molid': 5,
  'molecule': 'C2H2',
  'molhtml': 'C<sub>2</sub>H<sub>2</sub>',
  'moltag': 'c2h2',
  'molname': 'Acetylene',
  'molmass': 26.038},
 {'molid': 6,
  'molecule': 'CaH',
  'molhtml': 'CaH',
  'moltag': 'cah',
  'molname': 'Calcium monohydride',
  'molmass': 41.086},
 {'molid': 7,
  'molecule': 'CN',
  'molhtml': 'CN',
  'moltag': 'cn',
  'molname': 'Cyano radical',
  'molmass': 26.018},
 {'molid': 8,
  'molecule': 'CO2',
  'molhtml': 'CO<sub>2</sub>',
  'moltag': 'co2',
  'molname': 'Carbon dioxide',
  'molmass': 44.009},
 {'molid': 9,
  'molecule': 'H2CO',
  'molhtml': 'H<sub>2</sub>CO',
  'moltag': 'h2co',
  'molname': 'Formaldehyde',
  'molmass': 30.026},
 {'molid': 10,
  'molecule': 'H2O',
  'molhtml': 'H<sub>2</sub>O',
  'moltag': 'h2o',
  'molname': 'Water',
  'molmass': 18.015},
 {'molid': 11,
  'molecule': 'H2S',
  'molhtml': 'H<sub>2</sub>S',
  'moltag': 'h2s',
  'molname': 'Hydrogen sulfide',
  'molmass': 34.076},
 {'molid': 12,
  'molecule': 'H3+',
  'molhtml': 'H<sub>3</sub><sup>+</sup>',
  'moltag': 'h3+',
  'molname': 'Trihydrogen cation',
  'molmass': 3.024},
 {'molid': 13,
  'molecule': 'H3O+',
  'molhtml': 'H<sub>3</sub>O<sup>+</sup>',
  'moltag': 'h3o+',
  'molname': 'Hydronium cation',
  'molmass': 19.023},
 {'molid': 14,
  'molecule': 'LiOH',
  'molhtml': 'LiOH',
  'moltag': 'lioh',
  'molname': 'Lithium hydroxide',
  'molmass': 23.947},
 {'molid': 15,
  'molecule': 'MgH',
  'molhtml': 'MgH',
  'moltag': 'mgh',
  'molname': 'Magnesium monohydride',
  'molmass': 25.313},
 {'molid': 16,
  'molecule': 'NH',
  'molhtml': 'NH',
  'moltag': 'nh',
  'molname': 'Imidogen',
  'molmass': 15.015},
 {'molid': 17,
  'molecule': 'NH3',
  'molhtml': 'NH<sub>3</sub>',
  'moltag': 'nh3',
  'molname': 'Ammonia',
  'molmass': 17.031},
 {'molid': 18,
  'molecule': 'NO',
  'molhtml': 'NO',
  'moltag': 'no',
  'molname': 'Nitric oxide',
  'molmass': 30.006},
 {'molid': 19,
  'molecule': 'SiN',
  'molhtml': 'SiN',
  'moltag': 'sin',
  'molname': 'Silicon nitride',
  'molmass': 42.092},
 {'molid': 20,
  'molecule': 'SiO',
  'molhtml': 'SiO',
  'moltag': 'sio',
  'molname': 'Silicon monoxide',
  'molmass': 44.084},
 {'molid': 21,
  'molecule': 'SO',
  'molhtml': 'SO',
  'moltag': 'so',
  'molname': 'Sulfur monoxide',
  'molmass': 48.059},
 {'molid': 22,
  'molecule': 'SO2',
  'molhtml': 'SO<sub>2</sub>',
  'moltag': 'so2',
  'molname': 'Sulfur dioxide',
  'molmass': 64.058},
 {'molid': 23,
  'molecule': 'TiO',
  'molhtml': 'TiO',
  'moltag': 'tio',
  'molname': 'Titanium oxide',
  'molmass': 63.866},
 {'molid': 24,
  'molecule': 'YO',
  'molhtml': 'YO',
  'moltag': 'yo',
  'molname': 'Yttrium monoxide',
  'molmass': 104.90484},
 {'molid': 25,
  'molecule': 'ZrO',
  'molhtml': 'ZrO',
  'moltag': 'zro',
  'molname': 'Zirconium oxide',
  'molmass': 107.223}]

In [38]:
context = {'columns': data.columns, 'rows': data.to_dict('records')}

In [4]:
from pyvalem.formula import Formula
from pyvalem.stateful_species import StatefulSpecies

mol_columns = ['ID', 'Molecule', 'Name']
data = pd.read_csv('~/ExoMolHR-web/res/molecules.csv', header=None, names=mol_columns)
# data['Molecule'] = [Formula(formula).html for formula in data['Molecule'].values]
data

,,,ID,Molecule,Name
molid,molecule,molhtml,moltag,molname,molmass
1,AlCl,AlCl,alcl,Aluminum monochloride,62.431538
2,AlH,AlH,alh,Aluminum hydride,27.989538
3,AlO,AlO,alo,Aluminum monoxide,42.980538
4,C2,C<sub>2</sub>,c2,Dicarbon,24.022000
5,C2H2,C<sub>2</sub>H<sub>2</sub>,c2h2,Acetylene,26.038000
6,CaH,CaH,cah,Calcium monohydride,41.086000
7,CN,CN,cn,Cyano radical,26.018000
8,CO2,CO<sub>2</sub>,co2,Carbon dioxide,44.009000
9,H2CO,H<sub>2</sub>CO,h2co,Formaldehyde,30.026000
10,H2O,H<sub>2</sub>O,h2o,Water,18.015000
11,H2S,H<sub>2</sub>S,h2s,Hydrogen sulfide,34.076000
12,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000
13,H3O+,H<sub>3</sub>O<sup>+</sup>,h3o+,Hydronium cation,19.023000
14,LiOH,LiOH,lioh,Lithium hydroxide,23.947000
15,MgH,MgH,mgh,Magnesium monohydride,25.313000
16,NH,NH,nh,Imidogen,15.015000
17,NH3,NH<sub>3</sub>,nh3,Ammonia,17.031000
18,NO,NO,no,Nitric oxide,30.006000
19,SiN,SiN,sin,Silicon nitride,42.092000
20,SiO,SiO,sio,Silicon monoxide,44.084000
21,SO,SO,so,Sulfur monoxide,48.059000
22,SO2,SO<sub>2</sub>,so2,Sulfur dioxide,64.058000
23,TiO,TiO,tio,Titanium oxide,63.866000
24,YO,YO,yo,Yttrium monoxide,104.904840
25,ZrO,ZrO,zro,Zirconium oxide,107.223000

In [40]:
data.to_dict('records')

[{'ID': 'moltag', 'Molecule': 'molname', 'Name': 'molmass'},
 {'ID': 'alcl', 'Molecule': 'Aluminum monochloride', 'Name': '62.431538'},
 {'ID': 'alh', 'Molecule': 'Aluminum hydride', 'Name': '27.989538'},
 {'ID': 'alo', 'Molecule': 'Aluminum monoxide', 'Name': '42.980538'},
 {'ID': 'c2', 'Molecule': 'Dicarbon', 'Name': '24.022000'},
 {'ID': 'c2h2', 'Molecule': 'Acetylene', 'Name': '26.038000'},
 {'ID': 'cah', 'Molecule': 'Calcium monohydride', 'Name': '41.086000'},
 {'ID': 'cn', 'Molecule': 'Cyano radical', 'Name': '26.018000'},
 {'ID': 'co2', 'Molecule': 'Carbon dioxide', 'Name': '44.009000'},
 {'ID': 'h2co', 'Molecule': 'Formaldehyde', 'Name': '30.026000'},
 {'ID': 'h2o', 'Molecule': 'Water', 'Name': '18.015000'},
 {'ID': 'h2s', 'Molecule': 'Hydrogen sulfide', 'Name': '34.076000'},
 {'ID': 'h3+', 'Molecule': 'Trihydrogen cation', 'Name': '3.024000'},
 {'ID': 'h3o+', 'Molecule': 'Hydronium cation', 'Name': '19.023000'},
 {'ID': 'lioh', 'Molecule': 'Lithium hydroxide', 'Name': '23.947000'},
 {'ID': 'mgh', 'Molecule': 'Magnesium monohydride', 'Name': '25.313000'},
 {'ID': 'nao', 'Molecule': 'Sodium oxide', 'Name': '38.988769'},
 {'ID': 'nh', 'Molecule': 'Imidogen', 'Name': '15.015000'},
 {'ID': 'nh3', 'Molecule': 'Ammonia', 'Name': '17.031000'},
 {'ID': 'no', 'Molecule': 'Nitric oxide', 'Name': '30.006000'},
 {'ID': 'sin', 'Molecule': 'Silicon nitride', 'Name': '42.092000'},
 {'ID': 'sio', 'Molecule': 'Silicon monoxide', 'Name': '44.084000'},
 {'ID': 'so', 'Molecule': 'Sulfur monoxide', 'Name': '48.059000'},
 {'ID': 'so2', 'Molecule': 'Sulfur dioxide', 'Name': '64.058000'},
 {'ID': 'tio', 'Molecule': 'Titanium oxide', 'Name': '63.866000'},
 {'ID': 'yo', 'Molecule': 'Yttrium monoxide', 'Name': '104.904840'},
 {'ID': 'zro', 'Molecule': 'Zirconium oxide', 'Name': '107.223000'}]

In [41]:
Formula('(1H)2(16O)').rmm

18.010564684

In [42]:
Formula('CN').html

'CN'

In [43]:
Formula('H2O').rmm

18.015

In [44]:
StatefulSpecies('(52Cr)(1H)').html

'<sup>52</sup>Cr<sup>1</sup>H'

In [45]:
Formula('(1H)2(16O)').html
# Formula('H2O').html
# Formula('H2O').mass

'<sup>1</sup>H<sub>2</sub><sup>16</sup>O'

In [46]:
Formula('(1H)2(16O)').html

'<sup>1</sup>H<sub>2</sub><sup>16</sup>O'

In [47]:
import csv_to_sqlite, sqlite3

# all the usual options are supported
options = csv_to_sqlite.CsvOptions(typing_style="full", encoding="windows-1250") 
input_files = ['/home/jingxin/ExoMolHR-web/res/molecules.csv'] # pass in a list of CSV files
csv_to_sqlite.write_csv(input_files, "../db.sqlite3", options)

Error on table /home/jingxin/ExoMolHR-web/res/molecules.csv:
 table [molecules] already exists
Written 0 rows into 1 tables in 0.001 seconds

0

In [49]:
# con = sqlite3.connect('/home/jingxin/ExoMolHR-web/exomolhr/db.sqlite3', check_same_thread=False)
# db = con.cursor()

# cursor = db.execute("SELECT ID,Molecule,Name FROM 'molecules'")
# rows = cursor.fetchall()
# rows

In [50]:
# con = sqlite3.connect('/home/jingxin/ExoMolHR-web/exomolhr/db.sqlite3', check_same_thread=False)
# db = con.cursor()
# cursor = db.execute("SELECT ID,Molecule,Name FROM 'molecules'")
# columns = ['ID', 'Molecule', 'Name']
# rows = [dict(zip(columns, row)) for row in cursor.fetchall()]
# rows

In [51]:
# [Formula(row['Molecule']).html for row in rows]

In [52]:
# import sqlite3
# import pandas as pd
# con = sqlite3.connect('/home/jingxin/ExoMolHR-web/exomolhr/db.sqlite3', check_same_thread=False)
# db = con.cursor()
# cursor = db.execute("SELECT id,formula,name,mass FROM 'chem_molecule'")
# rows = pd.DataFrame(cursor.fetchall(), columns=['id', 'formula', 'name', 'mass'])
# rows['slug'] = [Formula(formula).html for formula in rows['formula'].values]
# rows['mass'] = [Formula(formula).rmm for formula in rows['formula'].values]


# rows

In [53]:
# rows.set_index('id', inplace=True)

# conn = sqlite3.connect('/home/jingxin/ExoMolHR-web/exomolhr/db.sqlite3')

# rows.to_sql('chem_molecule', conn, if_exists='append')

# conn.close()

In [54]:
data = pd.read_csv('../res/molecules.csv', header=0)
data

,molid,molecule,molhtml,moltag,molname,molmass
0,1,AlCl,AlCl,alcl,Aluminum monochloride,62.431538
1,2,AlH,AlH,alh,Aluminum hydride,27.989538
2,3,AlO,AlO,alo,Aluminum monoxide,42.980538
3,4,C2,C<sub>2</sub>,c2,Dicarbon,24.022000
4,5,C2H2,C<sub>2</sub>H<sub>2</sub>,c2h2,Acetylene,26.038000
5,6,CaH,CaH,cah,Calcium monohydride,41.086000
6,7,CN,CN,cn,Cyano radical,26.018000
7,8,CO2,CO<sub>2</sub>,co2,Carbon dioxide,44.009000
8,9,H2CO,H<sub>2</sub>CO,h2co,Formaldehyde,30.026000
9,10,H2O,H<sub>2</sub>O,h2o,Water,18.015000
10,11,H2S,H<sub>2</sub>S,h2s,Hydrogen sulfide,34.076000
11,12,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000
12,13,H3O+,H<sub>3</sub>O<sup>+</sup>,h3o+,Hydronium cation,19.023000
13,14,LiOH,LiOH,lioh,Lithium hydroxide,23.947000
14,15,MgH,MgH,mgh,Magnesium monohydride,25.313000
15,16,NaO,NaO,nao,Sodium oxide,38.988769
16,17,NH,NH,nh,Imidogen,15.015000
17,18,NH3,NH<sub>3</sub>,nh3,Ammonia,17.031000
18,19,NO,NO,no,Nitric oxide,30.006000
19,20,SiN,SiN,sin,Silicon nitride,42.092000
20,21,SiO,SiO,sio,Silicon monoxide,44.084000
21,22,SO,SO,so,Sulfur monoxide,48.059000
22,23,SO2,SO<sub>2</sub>,so2,Sulfur dioxide,64.058000
23,24,TiO,TiO,tio,Titanium oxide,63.866000
24,25,YO,YO,yo,Yttrium monoxide,104.904840
25,26,ZrO,ZrO,zro,Zirconium oxide,107.223000

In [55]:
context = {'columns': data.columns, 'rows': data.to_dict('records'), 'mol':'H2O'}

In [56]:
context.get('mol')

'H2O'

In [2]:
a= '(1H)2(16O)'
if '(' in a:
    print('a')

a

In [5]:
pieces_df = pd.read_csv('~/ExoMolHR-web/res/exomolhr.csv', header=0)
pieces_df

,id,filename,molecule,molhtml,moltag,molname,molmass,isoslug,isoformula,isohtml,isohtml.1,isotag,isohtml.2,isohtml.3,isomass,dataset
0,1,AlCl__27Al-35Cl__YNAT__(27Al)(35Cl).csv,AlCl,AlCl,alcl,Aluminum monochloride,62.431538,27Al-35Cl,(27Al)(35Cl),<sup>27</sup>Al<sup>35</sup>Cl,<sup>27</sup>Al<sup>35</sup>Cl,27al35cl,<sup>27</sup>Al<sup>35</sup>Cl,<sup>27</sup>Al<sup>35</sup>Cl,61.950391,YNAT
1,2,AlCl__27Al-37Cl__YNAT__(27Al)(37Cl).csv,AlCl,AlCl,alcl,Aluminum monochloride,62.431538,27Al-37Cl,(27Al)(37Cl),<sup>27</sup>Al<sup>37</sup>Cl,<sup>27</sup>Al<sup>37</sup>Cl,27al37cl,<sup>27</sup>Al<sup>37</sup>Cl,<sup>27</sup>Al<sup>37</sup>Cl,63.947441,YNAT
2,3,AlH__27Al-1H__AloHa__(27Al)(1H).csv,AlH,AlH,alh,Aluminum hydride,27.989538,27Al-1H,(27Al)(1H),<sup>27</sup>Al<sup>1</sup>H,<sup>27</sup>Al<sup>1</sup>H,27al1h,<sup>27</sup>Al<sup>1</sup>H,<sup>27</sup>Al<sup>1</sup>H,27.989363,AloHa
3,4,AlO__26Al-16O__ATP__(26Al)(16O).csv,AlO,AlO,alo,Aluminum monoxide,42.980538,26Al-16O,(26Al)(16O),<sup>26</sup>Al<sup>16</sup>O,<sup>26</sup>Al<sup>16</sup>O,26al16o,<sup>26</sup>Al<sup>16</sup>O,<sup>26</sup>Al<sup>16</sup>O,41.981806,ATP
4,5,AlO__27Al-16O__ATP__(27Al)(16O).csv,AlO,AlO,alo,Aluminum monoxide,42.980538,27Al-16O,(27Al)(16O),<sup>27</sup>Al<sup>16</sup>O,<sup>27</sup>Al<sup>16</sup>O,27al16o,<sup>27</sup>Al<sup>16</sup>O,<sup>27</sup>Al<sup>16</sup>O,42.976453,ATP
5,6,AlO__27Al-17O__ATP__(27Al)(17O).csv,AlO,AlO,alo,Aluminum monoxide,42.980538,27Al-17O,(27Al)(17O),<sup>27</sup>Al<sup>17</sup>O,<sup>27</sup>Al<sup>17</sup>O,27al17o,<sup>27</sup>Al<sup>17</sup>O,<sup>27</sup>Al<sup>17</sup>O,43.980670,ATP
6,7,AlO__27Al-18O__ATP__(27Al)(18O).csv,AlO,AlO,alo,Aluminum monoxide,42.980538,27Al-18O,(27Al)(18O),<sup>27</sup>Al<sup>18</sup>O,<sup>27</sup>Al<sup>18</sup>O,27al18o,<sup>27</sup>Al<sup>18</sup>O,<sup>27</sup>Al<sup>18</sup>O,44.980698,ATP
7,8,C2__12C2__8states__(12C)2.csv,C2,C<sub>2</sub>,c2,Dicarbon,24.022000,12C2,(12C)2,<sup>12</sup>C<sub>2</sub>,<sup>12</sup>C<sub>2</sub>,12c2,<sup>12</sup>C<sub>2</sub>,<sup>12</sup>C<sub>2</sub>,24.000000,8states
8,9,C2H2__12C2-1H2__aCeTY__(12C)2(1H)2.csv,C2H2,C<sub>2</sub>H<sub>2</sub>,c2h2,Acetylene,26.038000,12C2-1H2,(12C)2(1H)2,<sup>12</sup>C<sub>2</sub><sup>1</sup>H<sub>2<...,<sup>12</sup>C<sub>2</sub><sup>1</sup>H<sub>2<...,12c21h2,<sup>12</sup>C<sub>2</sub><sup>1</sup>H<sub>2<...,<sup>12</sup>C<sub>2</sub><sup>1</sup>H<sub>2<...,26.015650,aCeTY
9,10,CaH__40Ca-1H__XAB__(40Ca)(1H).csv,CaH,CaH,cah,Calcium monohydride,41.086000,40Ca-1H,(40Ca)(1H),<sup>40</sup>Ca<sup>1</sup>H,<sup>40</sup>Ca<sup>1</sup>H,40ca1h,<sup>40</sup>Ca<sup>1</sup>H,<sup>40</sup>Ca<sup>1</sup>H,40.970416,XAB
10,11,CN__12C-14N__Trihybrid__(12C)(14N).csv,CN,CN,cn,Cyano radical,26.018000,12C-14N,(12C)(14N),<sup>12</sup>C<sup>14</sup>N,<sup>12</sup>C<sup>14</sup>N,12c14n,<sup>12</sup>C<sup>14</sup>N,<sup>12</sup>C<sup>14</sup>N,26.003074,Trihybrid
11,12,CO2__12C-16O2__UCL-4000__(12C)(16O)2.csv,CO2,CO<sub>2</sub>,co2,Carbon dioxide,44.009000,12C-16O2,(12C)(16O)2,<sup>12</sup>C<sup>16</sup>O<sub>2</sub>,<sup>12</sup>C<sup>16</sup>O<sub>2</sub>,12c16o2,<sup>12</sup>C<sup>16</sup>O<sub>2</sub>,<sup>12</sup>C<sup>16</sup>O<sub>2</sub>,43.989829,UCL-4000
12,13,H2CO__1H2-12C-16O__AYTY__(1H)2(12C)(16O).csv,H2CO,H<sub>2</sub>CO,h2co,Formaldehyde,30.026000,1H2-12C-16O,(1H)2(12C)(16O),<sup>1</sup>H<sub>2</sub><sup>12</sup>C<sup>16...,<sup>1</sup>H<sub>2</sub><sup>12</sup>C<sup>16...,1h212c16o,<sup>1</sup>H<sub>2</sub><sup>12</sup>C<sup>16...,<sup>1</sup>H<sub>2</sub><sup>12</sup>C<sup>16...,30.010565,AYTY
13,14,H2O__1H2-16O__POKAZATEL__(1H)2(16O).csv,H2O,H<sub>2</sub>O,h2o,Water,18.015000,1H2-16O,(1H)2(16O),<sup>1</sup>H<sub>2</sub><sup>16</sup>O,<sup>1</sup>H<sub>2</sub><sup>16</sup>O,1h216o,<sup>1</sup>H<sub>2</sub><sup>16</sup>O,<sup>1</sup>H<sub>2</sub><sup>16</sup>O,18.010565,POKAZATEL
14,15,H2S__1H2-32S__AYT2__(1H)2(32S).csv,H2S,H<sub>2</sub>S,h2s,Hydrogen sulfide,34.076000,1H2-32S,(1H)2(32S),<sup>1</sup>H<sub>2</sub><sup>32</sup>S,<sup>1</sup>H<sub>2</sub><sup>32</sup>S,1h232s,<sup>1</sup>H<sub>2</sub><sup>32</sup>S,<sup>1</sup>H<sub>2</sub><sup>32</sup>S,33.987721,AYT2
15,16,H3_p__1H2-2H_p__ST__(1H)2(2H)+.csv,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000,1H2-2H+,(1H)2(2H)+,<sup>1</sup>H<sub>2</sub><sup>2</sup>H<sup>+</...,<sup>1</sup>H<sub>2</sub><sup>2</sup>H<sup>+</...,1h22h+,<sup>1</sup>H<sub>2</sub><sup>2</sup>H<sup>+</...,<sup>1</sup>H<sub>2</sub><sup>2</sup>H<sup>+</...,4.029752,ST
16,17,H3_p__1H3_p__MiZATeP__(1H)3+.csv,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000,1H3+,(1H)3+,<sup>1</sup>H<sub>3</sub><sup>+</sup>,<sup>1</sup>H<sub>3</sub><sup>+</sup>,1h3+,<sup>1</sup>H<sub>3</sub><sup>+</sup>,<sup>1</sup>H<sub>3</sub><sup>+</sup>,3.023475,MiZATeP
17,18,H3_p__2H2-1H_p__MiZo__(2H)2(1H)+.csv,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000,2H2-1H+,(2H)2(1H)+,<sup>2</sup>H<sub>2</sub><sup>1</sup>H<sup>+</...,<sup>2</sup>H<sub>2</sub><sup>1</sup>H<sup>+</...,2h21h+,<sup>2</sup>H<sub>2</sub><sup>1</sup>H<sup>+</...,<sup>2</sup>H<sub>2</sub><sup>1</sup>H<sup>+</...,5.036029,MiZo
18,19,H3_p__2H3_p__MiZo__(2H)3+.csv,H3+,H<sub>3</sub><sup>+</sup>,h3+,Trihydrogen cation,3.024000,2H3+,(2H)3+,<sup>2</sup>H<sub>3</sub><sup>+</sup>,<sup>2</sup>H<sub>3</sub><sup>+</sup>,2h3+,<sup>2</sup>H<sub>3</sub><sup>+</sup>,<sup>2</sup>H<sub>3</sub><sup>+</sup>,6.042305,MiZo
19,20,H3O_p__1H3-16O_p__eXeL__(1H)3(16O)+.csv,H3O+,H<sub>3</sub>O<sup>+</sup>,h3o+,Hydronium cation,19.023000,1H3-16O+,(1H)3(16O)+,<sup>1</sup>H<sub>3</sub><sup>16</sup>O<sup>+<...,<sup>1</sup>H<sub>3</sub><sup>16</sup>O<sup>+<...,1h316o+,<sup>1</sup>H<sub>3</sub><sup>16</sup>O<sup>+<...,<sup>1</sup>H<sub>3</sub><sup>16</sup>O<sup>+<...,19.018390,eXeL
20,21,LiOH__6Li-16O-1H__OYT7__(6Li)(16O)(1H).csv,LiOH,LiOH,lioh,Lithium hydroxide,23.947000,6Li-16O-1H,(6Li)(16O)(1H),<sup>6</sup>Li<sup>16</sup>O<sup>1</sup>H,<sup>6</sup>Li<sup>16</sup>O<sup>1</sup>H,6li16o1h,<sup>6</sup>Li<sup>16</sup>O<sup>1</sup>H,<sup>6</sup>Li<sup>16</sup>O<sup>1</sup>H,23.017863,OYT7
21,22,LiOH__7Li-16O-1H__OYT7__(7Li)(16O)(1H).csv,LiOH,LiOH,lioh,Lithium hydroxide,23.947000,7Li-16O-1H,(7Li)(16O)(1H),<sup>7</sup>Li<sup>16</sup>O<sup>1</sup>H,<sup>7</sup>Li<sup>16</sup>O<sup>1</sup>H,7li16o1h,<sup>7</sup>Li<sup>16</sup>O<sup>1</sup>H,<sup>7</sup>Li<sup>16</sup>O<sup>1</sup>H,24.018743,OYT7
22,23,MgH__24Mg-1H__XAB__(24Mg)(1H).csv,MgH,MgH,mgh,Magnesium monohydride,25.313000,24Mg-1H,(24Mg)(1H),<sup>24</sup>Mg<sup>1</sup>H,<sup>24</sup>Mg<sup>1</sup>H,24mg1h,<sup>24</sup>Mg<sup>1</sup>H,<sup>24</sup>Mg<sup>1</sup>H,24.992867,XAB
23,24,MgH__25Mg-1H__XAB__(25Mg)(1H).csv,MgH,MgH,mgh,Magnesium monohydride,25.313000,25Mg-1H,(25Mg)(1H),<sup>25</sup>Mg<sup>1</sup>H,<sup>25</sup>Mg<sup>1</sup>H,25mg1h,<sup>25</sup>Mg<sup>1</sup>H,<sup>25</sup>Mg<sup>1</sup>H,25.993662,XAB
24,25,MgH__26Mg-1H__XAB__(26Mg)(1H).csv,MgH,MgH,mgh,Magnesium monohydride,25.313000,26Mg-1H,(26Mg)(1H),<sup>26</sup>Mg<sup>1</sup>H,<sup>26</sup>Mg<sup>1</sup>H,26mg1h,<sup>26</sup>Mg<sup>1</sup>H,<sup>26</sup>Mg<sup>1</sup>H,26.990418,XAB
25,26,NH__14N-1H__kNigHt__(14N)(1H).csv,NH,NH,nh,Imidogen,15.015000,14N-1H,(14N)(1H),<sup>14</sup>N<sup>1</sup>H,<sup>14</sup>N<sup>1</sup>H,14n1h,<sup>14</sup>N<sup>1</sup>H,<sup>14</sup>N<sup>1</sup>H,15.010899,kNigHt
26,27,NH__14N-2H__kNigHt__(14N)(2H).csv,NH,NH,nh,Imidogen,15.015000,14N-2H,(14N)(2H),<sup>14</sup>N<sup>2</sup>H,<sup>14</sup>N<sup>2</sup>H,14n2h,<sup>14</sup>N<sup>2</sup>H,<sup>14</sup>N<sup>2</sup>H,16.017176,kNigHt
27,28,NH__15N-1H__kNigHt__(15N)(1H).csv,NH,NH,nh,Imidogen,15.015000,15N-1H,(15N)(1H),<sup>15</sup>N<sup>1</sup>H,<sup>15</sup>N<sup>1</sup>H,15n1h,<sup>15</sup>N<sup>1</sup>H,<sup>15</sup>N<sup>1</sup>H,16.007934,kNigHt
28,29,NH__15N-2H__kNigHt__(15N)(2H).csv,NH,NH,nh,Imidogen,15.015000,15N-2H,(15N)(2H),<sup>15</sup>N<sup>2</sup>H,<sup>15</sup>N<sup>2</sup>H,15n2h,<sup>15</sup>N<sup>2</sup>H,<sup>15</sup>N<sup>2</sup>H,17.014211,kNigHt
29,30,NH3__14N-1H3__CoYuTe__(14N)(1H)3.csv,NH3,NH<sub>3</sub>,nh3,Ammonia,17.031000,14N-1H3,(14N)(1H)3,<sup>14</sup>N<sup>1</sup>H<sub>3</sub>,<sup>14</sup>N<sup>1</sup>H<sub>3</sub>,14n1h3,<sup>14</sup>N<sup>1</sup>H<sub>3</sub>,<sup>14</sup>N<sup>1</sup>H<sub>3</sub>,17.026549,CoYuTe
30,31,NO__14N-16O__XABC__(14N)(16O).csv,NO,NO,no,Nitric oxide,30.006000,14N-16O,(14N)(16O),<sup>14</sup>N<sup>16</sup>O,<sup>14</sup>N<sup>16</sup>O,14n16o,<sup>14</sup>N<sup>16</sup>O,<sup>14</sup>N<sup>16</sup>O,29.997989,XABC
31,32,SiN__28Si-14N__SiNfull__(28Si)(14N).csv,SiN,SiN,sin,Silicon nitride,42.092000,28Si-14N,(28Si)(14N),<sup>28</sup>Si<sup>14</sup>N,<sup>28</sup>Si<sup>14</sup>N,28si14n,<sup>28</sup>Si<sup>14</sup>N,<sup>28</sup>Si<sup>14</sup>N,41.980001,SiNfull
32,33,SiN__28Si-15N__SiNfull__(28Si)(15N).csv,SiN,SiN,sin,Silicon nitride,42.092000,28Si-15N,(28Si)(15N),<sup>28</sup>Si<sup>15</sup>N,<sup>28</sup>Si<sup>15</sup>N,28si15n,<sup>28</sup>Si<sup>15</sup>N,<sup>28</sup>Si<sup>15</sup>N,42.977035,SiNfull
33,34,SiN__29Si-14N__SiNfull__(29Si)(14N).csv,SiN,SiN,sin,Silicon nitride,42.092000,29Si-14N,(29Si)(14N),<sup>29</sup>Si<sup>14</sup>N,<sup>29</sup>Si<sup>14</sup>N,29si14n,<sup>29</sup>Si<sup>14</sup>N,<sup>29</sup>Si<sup>14</sup>N,42.979569,SiNfull
34,35,SiN__30Si-14N__SiNfull__(30Si)(14N).csv,SiN,SiN,sin,Silicon nitride,42.092000,30Si-14N,(30Si)(14N),<sup>30</sup>Si<sup>14</sup>N,<sup>30</sup>Si<sup>14</sup>N,30si14n,<sup>30</sup>Si<sup>14</sup>N,<sup>30</sup>Si<sup>14</sup>N,43.976844,SiNfull
35,36,SiO__28Si-16O__SiOUVenIR__(28Si)(16O).csv,SiO,SiO,sio,Silicon monoxide,44.084000,28Si-16O,(28Si)(16O),<sup>28</sup>Si<sup>16</sup>O,<sup>28</sup>Si<sup>16</sup>O,28si16o,<sup>28</sup>Si<sup>16</sup>O,<sup>28</sup>Si<sup>16</sup>O,43.971841,SiOUVenIR
36,37,SO__32S-16O__SOLIS__(32S)(16O).csv,SO,SO,so,Sulfur monoxide,48.059000,32S-16O,(32S)(16O),<sup>32</sup>S<sup>16</sup>O,<sup>32</sup>S<sup>16</sup>O,32s16o,<sup>32</sup>S<sup>16</sup>O,<sup>32</sup>S<sup>16</sup>O,47.966986,SOLIS
37,38,SO2__32S-16O2__ExoAmes__(32S)(16O)2.csv,SO2,SO<sub>2</sub>,so2,Sulfur dioxide,64.058000,32S-16O2,(32S)(16O)2,<sup>32</sup>S<sup>16</sup>O<sub>2</sub>,<sup>32</sup>S<sup>16</sup>O<sub>2</sub>,32s16o2,<sup>32</sup>S<sup>16</sup>O<sub>2</sub>,<sup>32</sup>S<sup>16</sup>O<sub>2</sub>,63.961900,ExoAmes
38,39,TiO__48Ti-16O__Toto__(48Ti)(16O).csv,TiO,TiO,tio,Titanium oxide,63.866000,48Ti-16O,(48Ti)(16O),<sup>48</sup>Ti<sup>16</sup>O,<sup>48</sup>Ti<sup>16</sup>O,48ti16o,<sup>48</sup>Ti<sup>16</sup>O,<sup>48</sup>Ti<sup>16</sup>O,63.942856,Toto
39,40,YO__89Y-16O__BRYTS__(89Y)(16O).csv,YO,YO,yo,Yttrium monoxide,104.904840,89Y-16O,(89Y)(16O),<sup>89</sup>Y<sup>16</sup>O,<sup>89</sup>Y<sup>16</sup>O,89y16o,<sup>89</sup>Y<sup>16</sup>O,<sup>89</sup>Y<sup>16</sup>O,104.900756,BRYTS
40,41,YO__89Y-17O__BRYTS__(89Y)(17O).csv,YO,YO,yo,Yttrium monoxide,104.904840,89Y-17O,(89Y)(17O),<sup>89</sup>Y<sup>17</sup>O,<sup>89</sup>Y<sup>17</sup>O,89y17o,<sup>89</sup>Y<sup>17</sup>O,<sup>89</sup>Y<sup>17</sup>O,105.904973,BRYTS
41,42,YO__89Y-18O__BRYTS__(89Y)(18O).csv,YO,YO,yo,Yttrium monoxide,104.904840,89Y-18O,(89Y)(18O),<sup>89</sup>Y<sup>18</sup>O,<sup>89</sup>Y<sup>18</sup>O,89y18o,<sup>89</sup>Y<sup>18</sup>O,<sup>89</sup>Y<sup>18</sup>O,106.905001,BRYTS
42,43,ZrO__90Zr-16O__ZorrO__(90Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,90Zr-16O,(90Zr)(16O),<sup>90</sup>Zr<sup>16</sup>O,<sup>90</sup>Zr<sup>16</sup>O,90zr16o,<sup>90</sup>Zr<sup>16</sup>O,<sup>90</sup>Zr<sup>16</sup>O,105.899613,ZorrO
43,44,ZrO__91Zr-16O__ZorrO__(91Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,91Zr-16O,(91Zr)(16O),<sup>91</sup>Zr<sup>16</sup>O,<sup>91</sup>Zr<sup>16</sup>O,91zr16o,<sup>91</sup>Zr<sup>16</sup>O,<sup>91</sup>Zr<sup>16</sup>O,106.900555,ZorrO
44,45,ZrO__92Zr-16O__ZorrO__(92Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,92Zr-16O,(92Zr)(16O),<sup>92</sup>Zr<sup>16</sup>O,<sup>92</sup>Zr<sup>16</sup>O,92zr16o,<sup>92</sup>Zr<sup>16</sup>O,<sup>92</sup>Zr<sup>16</sup>O,107.899950,ZorrO
45,46,ZrO__93Zr-16O__ZorrO__(93Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,93Zr-16O,(93Zr)(16O),<sup>93</sup>Zr<sup>16</sup>O,<sup>93</sup>Zr<sup>16</sup>O,93zr16o,<sup>93</sup>Zr<sup>16</sup>O,<sup>93</sup>Zr<sup>16</sup>O,108.901385,ZorrO
46,47,ZrO__94Zr-16O__ZorrO__(94Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,94Zr-16O,(94Zr)(16O),<sup>94</sup>Zr<sup>16</sup>O,<sup>94</sup>Zr<sup>16</sup>O,94zr16o,<sup>94</sup>Zr<sup>16</sup>O,<sup>94</sup>Zr<sup>16</sup>O,109.901227,ZorrO
47,48,ZrO__96Zr-16O__ZorrO__(96Zr)(16O).csv,ZrO,ZrO,zro,Zirconium oxide,107.223000,96Zr-16O,(96Zr)(16O),<sup>96</sup>Zr<sup>16</sup>O,<sup>96</sup>Zr<sup>16</sup>O,96zr16o,<sup>96</sup>Zr<sup>16</sup>O,<sup>96</sup>Zr<sup>16</sup>O,111.903192,ZorrO

In [7]:
pieces_df = pd.read_csv('~/ExoMolHR-web/res/exomolhr.csv', header=0)
molecule = 'AlH'
isotopologue = '27Al-1H'
dataset = 'AloHa'

In [5]:
csvinf_df = pieces_df[pieces_df[['molecule', 'isoslug']].isin([molecule, isotopologue, dataset]).all(axis=1)]
localcsv_filename = csvinf_df['filename'].values[0]
localcsv_filepath = '/home/jingxin/data/exomolhr/loc_result/'+localcsv_filename
csv_fp = open(localcsv_filepath, 'r')
reader = csv.DictReader(csv_fp)
headers = [col for col in reader.fieldnames]

In [6]:
[col.replace('Sigma','<&Sigma;>') for col in reader.fieldnames]

['Frequency',
 'Uncertainty',
 'A',
 'E"',
 "g'",
 'g"',
 "J'",
 'J"',
 "+/-'",
 "e/f'",
 "ElecState'",
 "v'",
 "Lambda'",
 "<&Sigma;>'",
 "Omega'",
 '+/-"',
 'e/f"',
 'ElecState"',
 'v"',
 'Lambda"',
 '<&Sigma;>"',
 'Omega"']

In [7]:
headers

['Frequency',
 'Uncertainty',
 'A',
 'E"',
 "g'",
 'g"',
 "J'",
 'J"',
 "+/-'",
 "e/f'",
 "ElecState'",
 "v'",
 "Lambda'",
 "Sigma'",
 "Omega'",
 '+/-"',
 'e/f"',
 'ElecState"',
 'v"',
 'Lambda"',
 'Sigma"',
 'Omega"']

In [6]:
localcsv_filename = 'AlCl__27Al-35Cl__YNAT__(27Al)(35Cl).csv'
localcsv_filepath = '/home/jingxin/data/exomolhr/loc_result/'+localcsv_filename
csv_df = pd.read_csv(localcsv_filepath, dtype=str).head(200)
csv_df

,Frequency,Uncertainty,A,"E""",g',"g""",J',"J""",+/-',e/f',...,Lambda',Sigma',Omega',"+/-""","e/f""","ElecState""","v""","Lambda""","Sigma""","Omega"""
0,13557.002135,0.006325,3.2240E+01,24680.952623,72,120,1,2,-,e,...,-1,0,-1,+,e,a(3PI),0,1,-1,0
1,13557.979253,0.008485,9.6731E+01,24680.952623,120,120,2,2,-,f,...,-1,0,-1,+,e,a(3PI),0,1,-1,0
2,13558.015119,0.002828,9.6746E+01,24679.939606,72,72,1,1,+,f,...,1,0,1,-,e,a(3PI),0,-1,1,0
3,13558.502875,0.008485,5.5915E-11,24680.429102,120,120,2,2,+,e,...,1,0,1,-,f,a(3PI),0,-1,1,0
4,13558.521664,0.002000,6.4506E+01,24679.433094,72,24,1,0,-,e,...,-1,0,-1,+,e,a(3PI),0,1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,43525.415115,0.002010,6.0327E-02,0.486228,72,72,1,1,+,f,...,0,1,1,-,e,X(1SIGMA+),0,0,0,0
97,43526.327921,0.002000,5.7197E-02,0.000000,72,24,1,0,-,e,...,0,-1,-1,+,e,X(1SIGMA+),0,0,0,0
98,43526.755170,0.006003,5.1516E-02,0.486228,120,72,2,1,+,e,...,0,1,1,-,e,X(1SIGMA+),0,0,0,0
99,43526.815101,0.002010,2.5396E-02,0.486228,72,72,1,1,+,f,...,0,0,0,-,e,X(1SIGMA+),0,0,0,0
100,43527.205200,0.006030,3.1341E-02,1.458677,120,120,2,2,-,f,...,0,0,0,+,e,X(1SIGMA+),0,0,0,0

In [21]:
csv_df.to_dict('records')[4]

{'Frequency': '13558.521664',
 'Uncertainty': '    0.002000',
 'A': '6.4506E+01',
 'E"': '24679.433094',
 "g'": '    72',
 'g"': '    24',
 "J'": '      1',
 'J"': '      0',
 "+/-'": '-',
 "e/f'": 'e',
 "ElecState'": '      A(1PI)',
 "v'": '  0',
 "Lambda'": ' -1',
 "Sigma'": '    0',
 "Omega'": '   -1',
 '+/-"': '+',
 'e/f"': 'e',
 'ElecState"': '      a(3PI)',
 'v"': '  0',
 'Lambda"': '  1',
 'Sigma"': '   -1',
 'Omega"': '    0'}

In [13]:
csv_fp = open(localcsv_filepath, 'r')
reader = csv.DictReader(csv_fp)
headers = [col.replace('Sigma','Σ').replace('Lambda','Λ').replace('Omega','Ω') for col in reader.fieldnames]
out = [row for row in reader]
out

[{'Frequency': '13557.002135',
  'Uncertainty': '    0.006325',
  'A': '3.2240E+01',
  'E"': '24680.952623',
  "g'": '    72',
  'g"': '   120',
  "J'": '      1',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    0',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '   -1',
  'Omega"': '    0'},
 {'Frequency': '13557.979253',
  'Uncertainty': '    0.008485',
  'A': '9.6731E+01',
  'E"': '24680.952623',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'f',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    0',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '   -1',
  'Omega"': '    0'},
 {'Frequency': '13558.015119',
  'Uncertainty': '    0.002828',
  'A': '9.6746E+01',
  'E"': '24679.939606',
  "g'": '    72',
  'g"': '    72',
  "J'": '      1',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'f',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": '  1',
  "Sigma'": '    0',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    1',
  'Omega"': '    0'},
 {'Frequency': '13558.502875',
  'Uncertainty': '    0.008485',
  'A': '5.5915E-11',
  'E"': '24680.429102',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": '  1',
  "Sigma'": '    0',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'f',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    1',
  'Omega"': '    0'},
 {'Frequency': '13558.521664',
  'Uncertainty': '    0.002000',
  'A': '6.4506E+01',
  'E"': '24679.433094',
  "g'": '    72',
  'g"': '    24',
  "J'": '      1',
  'J"': '      0',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    0',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '   -1',
  'Omega"': '    0'},
 {'Frequency': '13558.538830',
  'Uncertainty': '    0.002828',
  'A': '6.2148E-12',
  'E"': '24679.415928',
  "g'": '    72',
  'g"': '    72',
  "J'": '      1',
  'J"': '      1',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    0',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'f',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '   -1',
  'Omega"': '    0'},
 {'Frequency': '13558.992371',
  'Uncertainty': '    0.006325',
  'A': '5.8054E+01',
  'E"': '24679.939606',
  "g'": '   120',
  'g"': '    72',
  "J'": '      2',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": '  1',
  "Sigma'": '    0',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    1',
  'Omega"': '    0'},
 {'Frequency': '13621.108803',
  'Uncertainty': '    0.006325',
  'A': '5.9057E-03',
  'E"': '24616.845955',
  "g'": '    72',
  'g"': '   120',
  "J'": '      1',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    0',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    0',
  'Omega"': '    1'},
 {'Frequency': '13622.085921',
  'Uncertainty': '    0.008485',
  'A': '1.7864E-02',
  'E"': '24616.845955',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'f',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    0',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    0',
  'Omega"': '    1'},
 {'Frequency': '13622.086283',
  'Uncertainty': '    0.008485',
  'A': '2.9629E-07',
  'E"': '24616.845694',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": '  1',
  "Sigma'": '    0',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'f',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    0',
  'Omega"': '   -1'},
 {'Frequency': '13622.114053',
  'Uncertainty': '    0.002828',
  'A': '5.9564E-03',
  'E"': '24615.840672',
  "g'": '    72',
  'g"': '    72',
  "J'": '      1',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'f',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": '  1',
  "Sigma'": '    0',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    0',
  'Omega"': '   -1'},
 {'Frequency': '13622.114173',
  'Uncertainty': '    0.002828',
  'A': '9.8793E-08',
  'E"': '24615.840585',
  "g'": '    72',
  'g"': '    72',
  "J'": '      1',
  'J"': '      1',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    0',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'f',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    0',
  'Omega"': '    1'},
 {'Frequency': '13623.091305',
  'Uncertainty': '    0.006325',
  'A': '3.5452E-03',
  'E"': '24615.840672',
  "g'": '   120',
  'g"': '    72',
  "J'": '      2',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": '  1',
  "Sigma'": '    0',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    0',
  'Omega"': '   -1'},
 {'Frequency': '13685.291591',
  'Uncertainty': '    0.006325',
  'A': '1.8027E-07',
  'E"': '24552.663167',
  "g'": '    72',
  'g"': '   120',
  "J'": '      1',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    0',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    1',
  'Omega"': '    2'},
 {'Frequency': '13686.268709',
  'Uncertainty': '    0.008485',
  'A': '5.4980E-07',
  'E"': '24552.663167',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'f',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    0',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    1',
  'Omega"': '    2'},
 {'Frequency': '13686.268810',
  'Uncertainty': '    0.008485',
  'A': '3.6550E-11',
  'E"': '24552.663167',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '      A(1PI)',
  "v'": '  0',
  "Lambda'": '  1',
  "Sigma'": '    0',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'f',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '   -1',
  'Omega"': '   -2'},
 {'Frequency': '18845.375298',
  'Uncertainty': '    0.006325',
  'A': '1.7469E-08',
  'E"': '24680.952623',
  "g'": '    72',
  'g"': '   120',
  "J'": '      1',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '   -1',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '   -1',
  'Omega"': '    0'},
 {'Frequency': '18845.413091',
  'Uncertainty': '    0.008485',
  'A': '3.3343E-08',
  'E"': '24680.952623',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'f',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '   -1',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '   -1',
  'Omega"': '    0'},
 {'Frequency': '18845.961737',
  'Uncertainty': '    0.002828',
  'A': '3.6976E-08',
  'E"': '24679.939606',
  "g'": '    72',
  'g"': '    72',
  "J'": '      1',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'f',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    1',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    1',
  'Omega"': '    0'},
 {'Frequency': '18846.812296',
  'Uncertainty': '    0.008485',
  'A': '6.5656E-17',
  'E"': '24680.429102',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    1',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'f',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    1',
  'Omega"': '    0'},
 {'Frequency': '18846.894827',
  'Uncertainty': '    0.002000',
  'A': '3.5038E-08',
  'E"': '24679.433094',
  "g'": '    72',
  'g"': '    24',
  "J'": '      1',
  'J"': '      0',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '   -1',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '   -1',
  'Omega"': '    0'},
 {'Frequency': '18846.911993',
  'Uncertainty': '    0.002828',
  'A': '7.2998E-18',
  'E"': '24679.415928',
  "g'": '    72',
  'g"': '    72',
  "J'": '      1',
  'J"': '      1',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '   -1',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'f',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '   -1',
  'Omega"': '    0'},
 {'Frequency': '18847.301792',
  'Uncertainty': '    0.006325',
  'A': '3.1548E-08',
  'E"': '24679.939606',
  "g'": '   120',
  'g"': '    72',
  "J'": '      2',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    1',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    1',
  'Omega"': '    0'},
 {'Frequency': '18847.361723',
  'Uncertainty': '    0.002828',
  'A': '1.5536E-08',
  'E"': '24679.939606',
  "g'": '    72',
  'g"': '    72',
  "J'": '      1',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'f',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    0',
  "Omega'": '    0',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    1',
  'Omega"': '    0'},
 {'Frequency': '18847.711254',
  'Uncertainty': '    0.008485',
  'A': '1.9156E-08',
  'E"': '24680.952623',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'f',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    0',
  "Omega'": '    0',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '   -1',
  'Omega"': '    0'},
 {'Frequency': '18909.481966',
  'Uncertainty': '    0.006325',
  'A': '4.5277E-12',
  'E"': '24616.845955',
  "g'": '    72',
  'g"': '   120',
  "J'": '      1',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '   -1',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    0',
  'Omega"': '    1'},
 {'Frequency': '18909.519759',
  'Uncertainty': '    0.008485',
  'A': '6.1068E-12',
  'E"': '24616.845955',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'f',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '   -1',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    0',
  'Omega"': '    1'},
 {'Frequency': '18910.060671',
  'Uncertainty': '    0.002828',
  'A': '2.2577E-12',
  'E"': '24615.840672',
  "g'": '    72',
  'g"': '    72',
  "J'": '      1',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'f',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    1',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    0',
  'Omega"': '   -1'},
 {'Frequency': '18910.395704',
  'Uncertainty': '    0.008485',
  'A': '3.4485E-13',
  'E"': '24616.845694',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    1',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'f',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    0',
  'Omega"': '   -1'},
 {'Frequency': '18910.487336',
  'Uncertainty': '    0.002828',
  'A': '1.1502E-13',
  'E"': '24615.840585',
  "g'": '    72',
  'g"': '    72',
  "J'": '      1',
  'J"': '      1',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '   -1',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'f',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    0',
  'Omega"': '    1'},
 {'Frequency': '18911.400726',
  'Uncertainty': '    0.006325',
  'A': '2.7244E-12',
  'E"': '24615.840672',
  "g'": '   120',
  'g"': '    72',
  "J'": '      2',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    1',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    0',
  'Omega"': '   -1'},
 {'Frequency': '18911.460657',
  'Uncertainty': '    0.002828',
  'A': '9.4859E-13',
  'E"': '24615.840672',
  "g'": '    72',
  'g"': '    72',
  "J'": '      1',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'f',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    0',
  "Omega'": '    0',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '    0',
  'Omega"': '   -1'},
 {'Frequency': '18911.817922',
  'Uncertainty': '    0.008485',
  'A': '3.5083E-12',
  'E"': '24616.845955',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'f',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    0',
  "Omega'": '    0',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    0',
  'Omega"': '    1'},
 {'Frequency': '18973.664754',
  'Uncertainty': '    0.006325',
  'A': '1.8588E-16',
  'E"': '24552.663167',
  "g'": '    72',
  'g"': '   120',
  "J'": '      1',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '   -1',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    1',
  'Omega"': '    2'},
 {'Frequency': '18973.702547',
  'Uncertainty': '    0.008485',
  'A': '1.8641E-16',
  'E"': '24552.663167',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'f',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '   -1',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    1',
  'Omega"': '    2'},
 {'Frequency': '18974.578231',
  'Uncertainty': '    0.008485',
  'A': '4.2202E-17',
  'E"': '24552.663167',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    1',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'f',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': ' -1',
  'Sigma"': '   -1',
  'Omega"': '   -2'},
 {'Frequency': '18976.000710',
  'Uncertainty': '    0.008485',
  'A': '1.0708E-16',
  'E"': '24552.663167',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'f',
  "ElecState'": '  b(3SIGMA+)',
  "v'": '  0',
  "Lambda'": '  0',
  "Sigma'": '    0',
  "Omega'": '    0',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '      a(3PI)',
  'v"': '  0',
  'Lambda"': '  1',
  'Sigma"': '    1',
  'Omega"': '    2'},
 {'Frequency': '23664.809553',
  'Uncertainty': '    0.010198',
  'A': '1.1884E+01',
  'E"': '  951.031119',
  "g'": '    72',
  'g"': '    24',
  "J'": '      1',
  'J"': '      0',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '      a(3PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    0',
  "Omega'": '   -1',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '  X(1SIGMA+)',
  'v"': '  2',
  'Lambda"': '  0',
  'Sigma"': '    0',
  'Omega"': '    0'},
 {'Frequency': '23728.908487',
  'Uncertainty': '    0.010198',
  'A': '1.5119E-02',
  'E"': '  951.031119',
  "g'": '    72',
  'g"': '    24',
  "J'": '      1',
  'J"': '      0',
  "+/-'": '-',
  "e/f'": 'e',
  "ElecState'": '      a(3PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '    1',
  "Omega'": '    0',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '  X(1SIGMA+)',
  'v"': '  2',
  'Lambda"': '  0',
  'Sigma"': '    0',
  'Omega"': '    0'},
 {'Frequency': '24072.171970',
  'Uncertainty': '    0.008628',
  'A': '6.3026E-03',
  'E"': '  480.491197',
  "g'": '   120',
  'g"': '   168',
  "J'": '      2',
  'J"': '      3',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '      a(3PI)',
  "v'": '  0',
  "Lambda'": '  1',
  "Sigma'": '    1',
  "Omega'": '    2',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '  X(1SIGMA+)',
  'v"': '  1',
  'Lambda"': '  0',
  'Sigma"': '    0',
  'Omega"': '    0'},
 {'Frequency': '24073.621001',
  'Uncertainty': '    0.008207',
  'A': '1.5808E-02',
  'E"': '  479.042166',
  "g'": '   120',
  'g"': '   120',
  "J'": '      2',
  'J"': '      2',
  "+/-'": '-',
  "e/f'": 'f',
  "ElecState'": '      a(3PI)',
  "v'": '  0',
  "Lambda'": ' -1',
  "Sigma'": '   -1',
  "Omega'": '   -2',
  '+/-"': '+',
  'e/f"': 'e',
  'ElecState"': '  X(1SIGMA+)',
  'v"': '  1',
  'Lambda"': '  0',
  'Sigma"': '    0',
  'Omega"': '    0'},
 {'Frequency': '24074.587031',
  'Uncertainty': '    0.007940',
  'A': '9.5050E-03',
  'E"': '  478.076136',
  "g'": '   120',
  'g"': '    72',
  "J'": '      2',
  'J"': '      1',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '      a(3PI)',
  "v'": '  0',
  "Lambda'": '  1',
  "Sigma'": '    1',
  "Omega'": '    2',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '  X(1SIGMA+)',
  'v"': '  1',
  'Lambda"': '  0',
  'Sigma"': '    0',
  'Omega"': '    0'},
 {'Frequency': '24136.354758',
  'Uncertainty': '    0.008628',
  'A': '5.1188E+01',
  'E"': '  480.491197',
  "g'": '   120',
  'g"': '   168',
  "J'": '      2',
  'J"': '      3',
  "+/-'": '+',
  "e/f'": 'e',
  "ElecState'": '      a(3PI)',
  "v'": '  0',
  "Lambda'": '  1',
  "Sigma'": '    0',
  "Omega'": '    1',
  '+/-"': '-',
  'e/f"': 'e',
  'ElecState"': '  X(1SIGMA+)',
  'v"': '  1',
  'Lambda"': '  0',
  'Sigma"': '    0',
  'Omega"': '    0'},
 {'Frequency': '24136.798506',
  'Uncertainty': '    0.005946',
  'A': '4.2761E+01',
  'E"': '  479.042166',
  "g'": '    72',

In [15]:
pieces_df = pd.read_csv('~/ExoMolHR-web/res/exomolhr.csv', header=0)
selected_molecules = ['AlH','MgH']
selected_isotopologues = ['27Al-1H','24Mg-1H','26Mg-1H']
 
datasets_df = pieces_df[pieces_df[['molecule']].isin(selected_molecules).all(axis=1)]
datasets_df = datasets_df[datasets_df[['isoslug']].isin(selected_isotopologues).all(axis=1)]
datasets_df = datasets_df[['molecule', 'molhtml', 'molname', 
                            'isoslug', 'isoformula', 'isohtml', 'isotag', 'isomass',
                            'dataset', 'filename']].drop_duplicates()
datasets_df

,molecule,molhtml,molname,isoslug,isoformula,isohtml,isotag,isomass,dataset,filename
2,AlH,AlH,Aluminum hydride,27Al-1H,(27Al)(1H),<sup>27</sup>Al<sup>1</sup>H,27al1h,27.989363,AloHa,AlH__27Al-1H__AloHa__(27Al)(1H).csv
22,MgH,MgH,Magnesium monohydride,24Mg-1H,(24Mg)(1H),<sup>24</sup>Mg<sup>1</sup>H,24mg1h,24.992867,XAB,MgH__24Mg-1H__XAB__(24Mg)(1H).csv
24,MgH,MgH,Magnesium monohydride,26Mg-1H,(26Mg)(1H),<sup>26</sup>Mg<sup>1</sup>H,26mg1h,26.990418,XAB,MgH__26Mg-1H__XAB__(26Mg)(1H).csv

In [14]:

datasets_df['id'] = datasets_df.reset_index().index+1

In [5]:
pieces_df = pd.read_csv('~/ExoMolHR-web/res/exomolhr.csv', header=0)
selected_molecules = ['AlH','AlO','AlCl','AlCl']
selected_isotopologues = ['27Al-1H','27Al-16O','27Al-35Cl','27Al-37Cl']
selected_datasets = ['AloHa','YNAT']

In [6]:
list(set(selected_molecules))

['AlH', 'AlO', 'AlCl']

In [7]:
filters_df = pieces_df[pieces_df[['molecule']].isin(selected_molecules).all(axis=1)]
filters_df = filters_df[filters_df[['isoslug']].isin(selected_isotopologues).all(axis=1)]    
filters_df = filters_df[filters_df[['dataset']].isin(selected_datasets).all(axis=1)]   
# Get column names matching the pattern 'xxx.a'
columns_to_drop = filters_df.columns[filters_df.columns.str.match(r'[a-zA-Z]+\.\d+')]
# Drop columns that match the pattern
filters_df = filters_df.drop(columns=columns_to_drop)
filters_df['id'] = filters_df.reset_index().index+1
localcsv_filenames = filters_df['filename'].values

filters_df

,id,filename,molecule,molhtml,moltag,molname,molmass,isoslug,isoformula,isohtml,isotag,isomass,dataset
0,1,AlCl__27Al-35Cl__YNAT__(27Al)(35Cl).csv,AlCl,AlCl,alcl,Aluminum monochloride,62.431538,27Al-35Cl,(27Al)(35Cl),<sup>27</sup>Al<sup>35</sup>Cl,27al35cl,61.950391,YNAT
1,2,AlCl__27Al-37Cl__YNAT__(27Al)(37Cl).csv,AlCl,AlCl,alcl,Aluminum monochloride,62.431538,27Al-37Cl,(27Al)(37Cl),<sup>27</sup>Al<sup>37</sup>Cl,27al37cl,63.947441,YNAT
2,3,AlH__27Al-1H__AloHa__(27Al)(1H).csv,AlH,AlH,alh,Aluminum hydride,27.989538,27Al-1H,(27Al)(1H),<sup>27</sup>Al<sup>1</sup>H,27al1h,27.989363,AloHa

In [38]:
filters_df['molecule'].drop_duplicates().values

array(['AlCl', 'AlH'], dtype=object)

In [39]:
molecules_url = '_'.join(filters_df['molecule'].drop_duplicates().values)
molecules_url

'AlCl_AlH'

In [ ]:
# columns = ['id', 'filename', 'molecule', 'molhtml', 'moltag', 'molname', 'molmass', 
#            'isoslug', 'isoformula', 'isohtml', 'isotag', 'isomass', 'dataset']

In [23]:
filters_df.columns

Index(['id', 'filename', 'molecule', 'molhtml', 'moltag', 'molname', 'molmass',
       'isoslug', 'isoformula', 'isohtml', 'isotag', 'isomass', 'dataset'],
      dtype='object')

In [125]:
import pandas as pd

localcsv_filename = 'AlCl__27Al-35Cl__YNAT__(27Al)(35Cl).csv'
localcsv_filepath = "/mnt/data/exomolhr_data/loc_result/" + localcsv_filename
csv_df = pd.read_csv(localcsv_filepath, header=0)
csv_df

,Frequency,Uncertainty,A,"E""",g',"g""",J',"J""",+/-',e/f',...,Lambda',Sigma',Omega',"+/-""","e/f""","ElecState""","v""","Lambda""","Sigma""","Omega"""
0,13557.002135,0.006325,3.224000e+01,24680.952623,72,120,1,2,-,e,...,-1,0,-1,+,e,a(3PI),0,1,-1,0
1,13557.979253,0.008485,9.673100e+01,24680.952623,120,120,2,2,-,f,...,-1,0,-1,+,e,a(3PI),0,1,-1,0
2,13558.015119,0.002828,9.674600e+01,24679.939606,72,72,1,1,+,f,...,1,0,1,-,e,a(3PI),0,-1,1,0
3,13558.502875,0.008485,5.591500e-11,24680.429102,120,120,2,2,+,e,...,1,0,1,-,f,a(3PI),0,-1,1,0
4,13558.521664,0.002000,6.450600e+01,24679.433094,72,24,1,0,-,e,...,-1,0,-1,+,e,a(3PI),0,1,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,43525.415115,0.002010,6.032700e-02,0.486228,72,72,1,1,+,f,...,0,1,1,-,e,X(1SIGMA+),0,0,0,0
97,43526.327921,0.002000,5.719700e-02,0.000000,72,24,1,0,-,e,...,0,-1,-1,+,e,X(1SIGMA+),0,0,0,0
98,43526.755170,0.006003,5.151600e-02,0.486228,120,72,2,1,+,e,...,0,1,1,-,e,X(1SIGMA+),0,0,0,0
99,43526.815101,0.002010,2.539600e-02,0.486228,72,72,1,1,+,f,...,0,0,0,-,e,X(1SIGMA+),0,0,0,0
100,43527.205200,0.006030,3.134100e-02,1.458677,120,120,2,2,-,f,...,0,0,0,+,e,X(1SIGMA+),0,0,0,0

In [159]:
header_names = [col.replace('Sigma','Σ').replace('Lambda','Λ').replace('Omega','Ω') for col in csv_df.columns]
header_labels = [col.replace("'","").replace('"','') for col in header_names]
header_names_df = pd.DataFrame({'labelname':header_names, 'label':header_labels})
EXOMOL_DIR = '/mnt/data/exomol/exomol3_data/'
species_folder = '/'.join(localcsv_filename.split('__')[:3]) 
def_json_filename = '__'.join(localcsv_filename.split('__')[1:3]) + '.json'
def_json_path = EXOMOL_DIR + species_folder + '/' + def_json_filename
def_json_df = pd.read_json(def_json_path, orient='columns')
states_col_dict = def_json_df['dataset']['states']['states_file_fields']
states_col_df = pd.DataFrame(states_col_dict)
states_col_df['name'] = states_col_df['name'].str.replace('gtot','g')
states_col_df['label'] = [col.split(':')[-1].replace('Sigma','Σ').replace('Lambda','Λ').replace('Omega','Ω') 
                          for col in states_col_df['name'].values]
states_col_df['desc'] = '<br/>Description: ' + states_col_df['desc'].str.replace('-1','<sup>-1</sup>')
states_col_df['fmt'] = ('Fortran format | C format<br/><code>' + states_col_df['ffmt'].str
                        .cat(states_col_df['cfmt'], sep='</code> | <code>') + '</code>')
header_details_df = pd.merge(states_col_df, header_names_df, on='label')
header_details_df['labelname'] = ('Label: ' + header_details_df['labelname'].str
                                  .replace("'", "' for upper state").str.replace('"','" for lower state'))

header_details_df

,name,desc,ffmt,cfmt,label,fmt,labelname
0,E,<br/>Description: State energy in cm<sup>-1</sup>,F12.6,%12.6f,E,Fortran format | C format<br/><code>F12.6</cod...,"Label: E"" for lower state"
1,g,<br/>Description: Total energy level degeneracy,I6,%6d,g,Fortran format | C format<br/><code>I6</code> ...,Label: g' for upper state
2,g,<br/>Description: Total energy level degeneracy,I6,%6d,g,Fortran format | C format<br/><code>I6</code> ...,"Label: g"" for lower state"
3,J,<br/>Description: Total rotational quantum num...,I7,%7d,J,Fortran format | C format<br/><code>I7</code> ...,Label: J' for upper state
4,J,<br/>Description: Total rotational quantum num...,I7,%7d,J,Fortran format | C format<br/><code>I7</code> ...,"Label: J"" for lower state"
5,hunda:+/-,<br/>Description: Parity,A1,%1s,+/-,Fortran format | C format<br/><code>A1</code> ...,Label: +/-' for upper state
6,hunda:+/-,<br/>Description: Parity,A1,%1s,+/-,Fortran format | C format<br/><code>A1</code> ...,"Label: +/-"" for lower state"
7,hunda:e/f,<br/>Description: Rotationless-parity,A1,%1s,e/f,Fortran format | C format<br/><code>A1</code> ...,Label: e/f' for upper state
8,hunda:e/f,<br/>Description: Rotationless-parity,A1,%1s,e/f,Fortran format | C format<br/><code>A1</code> ...,"Label: e/f"" for lower state"
9,hunda:ElecState,<br/>Description: Electronic state,A12,%12s,ElecState,Fortran format | C format<br/><code>A12</code>...,Label: ElecState' for upper state
10,hunda:ElecState,<br/>Description: Electronic state,A12,%12s,ElecState,Fortran format | C format<br/><code>A12</code>...,"Label: ElecState"" for lower state"
11,hunda:v,<br/>Description: State vibrational quantum nu...,I3,%3d,v,Fortran format | C format<br/><code>I3</code> ...,Label: v' for upper state
12,hunda:v,<br/>Description: State vibrational quantum nu...,I3,%3d,v,Fortran format | C format<br/><code>I3</code> ...,"Label: v"" for lower state"
13,hunda:Lambda,<br/>Description: Projection of the electronic...,I3,%3d,Λ,Fortran format | C format<br/><code>I3</code> ...,Label: Λ' for upper state
14,hunda:Lambda,<br/>Description: Projection of the electronic...,I3,%3d,Λ,Fortran format | C format<br/><code>I3</code> ...,"Label: Λ"" for lower state"
15,hunda:Sigma,<br/>Description: Projection of the electronic...,I5,%5d,Σ,Fortran format | C format<br/><code>I5</code> ...,Label: Σ' for upper state
16,hunda:Sigma,<br/>Description: Projection of the electronic...,I5,%5d,Σ,Fortran format | C format<br/><code>I5</code> ...,"Label: Σ"" for lower state"
17,hunda:Omega,<br/>Description: Projection of the total angu...,I5,%5d,Ω,Fortran format | C format<br/><code>I5</code> ...,Label: Ω' for upper state
18,hunda:Omega,<br/>Description: Projection of the total angu...,I5,%5d,Ω,Fortran format | C format<br/><code>I5</code> ...,"Label: Ω"" for lower state"

In [154]:
states_col_df

,name,desc,ffmt,cfmt,label,fmt
0,ID,<br/>Description: Unique integer identifier fo...,I12,%12d,ID,Fortran format | C format<br/><code>I12</code>...
1,E,<br/>Description: State energy in cm<sup>-1</sup>,F12.6,%12.6f,E,Fortran format | C format<br/><code>F12.6</cod...
2,g,<br/>Description: Total energy level degeneracy,I6,%6d,g,Fortran format | C format<br/><code>I6</code> ...
3,J,<br/>Description: Total rotational quantum num...,I7,%7d,J,Fortran format | C format<br/><code>I7</code> ...
4,unc,<br/>Description: Energy uncertainty in cm<sup...,F12.6,%12.6f,unc,Fortran format | C format<br/><code>F12.6</cod...
5,hunda:+/-,<br/>Description: Parity,A1,%1s,+/-,Fortran format | C format<br/><code>A1</code> ...
6,hunda:e/f,<br/>Description: Rotationless-parity,A1,%1s,e/f,Fortran format | C format<br/><code>A1</code> ...
7,hunda:ElecState,<br/>Description: Electronic state,A12,%12s,ElecState,Fortran format | C format<br/><code>A12</code>...
8,hunda:v,<br/>Description: State vibrational quantum nu...,I3,%3d,v,Fortran format | C format<br/><code>I3</code> ...
9,hunda:Lambda,<br/>Description: Projection of the electronic...,I3,%3d,Λ,Fortran format | C format<br/><code>I3</code> ...
10,hunda:Sigma,<br/>Description: Projection of the electronic...,I5,%5d,Σ,Fortran format | C format<br/><code>I5</code> ...
11,hunda:Omega,<br/>Description: Projection of the total angu...,I5,%5d,Ω,Fortran format | C format<br/><code>I5</code> ...

In [ ]:
main_tips = ['Label: Frenquency<br/>Description: Wavenumnber in cm<sup>-1</sup><br/>Fortran format | C format<br/><code>F12.6</code> | <code>%12.6f</code>',
'Label: Uncertainty<br/>Description: Description: Energy uncertainty in cm<sup>-1</sup><br/>Fortran format | C format<br/><code>F12.6</code> | <code>%12.6f</code>',
'Label: A<br/>Description: Einstein A coefficient<br/>Fortran format | C format<br/><code>ES10.4</code> | <code>%10.4E</code>']

In [149]:
main_cols = ['Frequency','Uncertainty','A']
main_desc = ['Wavenumber',
             'Uncertainty',
             'Einstein A coefficient']
main_
main_cols

['Frequency', 'Uncertainty', 'A', 'E"', "g'", 'g"', "J'", 'J"']

In [114]:
header_details_df['labelname'].str + '<br/>' + header_details_df['desc'].str + '<br/>' + header_details_df['fmt'].str

TypeError: unsupported operand type(s) for +: 'StringMethods' and 'str'

In [158]:
def get_tip(header_names, localcsv_filename):
    header_labels = [col.replace("'","").replace('"','') for col in header_names]
    header_names_df = pd.DataFrame({'labelname':header_names, 'label':header_labels})
    EXOMOL_DIR = '/mnt/data/exomol/exomol3_data/'
    species_folder = '/'.join(localcsv_filename.split('__')[:3]) 
    def_json_filename = '__'.join(localcsv_filename.split('__')[1:3]) + '.json'
    def_json_path = EXOMOL_DIR + species_folder + '/' + def_json_filename
    def_json_df = pd.read_json(def_json_path, orient='columns')
    states_col_dict = def_json_df['dataset']['states']['states_file_fields']
    states_col_df = pd.DataFrame(states_col_dict)
    states_col_df['name'] = states_col_df['name'].str.replace('gtot','g')
    states_col_df['label'] = [col.split(':')[-1].replace('Sigma','Σ').replace('Lambda','Λ').replace('Omega','Ω') 
                            for col in states_col_df['name'].values]
    states_col_df['desc'] = '<br/>Description: ' + states_col_df['desc'].str.replace('-1','<sup>-1</sup>')
    states_col_df['fmt'] = ('Fortran format | C format<br/><code>' + states_col_df['ffmt'].str
                            .cat(states_col_df['cfmt'], sep='</code> | <code>') + '</code>')
    header_details_df = pd.merge(states_col_df, header_names_df, on='label')
    header_details_df['labelname'] = ('Label: ' + header_details_df['labelname'].str
                                    .replace("'", "' for upper state").str.replace('"','" for lower state'))
    main_tips = ['Label: Frenquency<br/>Description: Wavenumnber in cm<sup>-1</sup><br/>Fortran format | C format<br/><code>F12.6</code> | <code>%12.6f</code>',
    'Label: Uncertainty<br/>Description: Description: Energy uncertainty in cm<sup>-1</sup><br/>Fortran format | C format<br/><code>F12.6</code> | <code>%12.6f</code>',
    'Label: A<br/>Description: Einstein A coefficient<br/>Fortran format | C format<br/><code>ES10.4</code> | <code>%10.4E</code>']
    other_tips = (header_details_df['labelname'].astype(str) + '<br/>' + 
                  header_details_df['desc'].astype(str) + '<br/>' + 
                  header_details_df['fmt'].astype(str)).tolist()
    head_tips = main_tips + other_tips
    return(head_tips)

In [160]:
header_names = [col.replace('Sigma','Σ').replace('Lambda','Λ').replace('Omega','Ω') for col in csv_df.columns]
head_tips = get_tip(header_names, localcsv_filename)
head_tips

['Label: Frenquency<br/>Description: Wavenumnber in cm<sup>-1</sup><br/>Fortran format | C format<br/><code>F12.6</code> | <code>%12.6f</code>',
 'Label: Uncertainty<br/>Description: Description: Energy uncertainty in cm<sup>-1</sup><br/>Fortran format | C format<br/><code>F12.6</code> | <code>%12.6f</code>',
 'Label: A<br/>Description: Einstein A coefficient<br/>Fortran format | C format<br/><code>ES10.4</code> | <code>%10.4E</code>',
 'Label: E" for lower state<br/>Description: State energy in cm<sup>-1</sup><br/>Fortran format | C format<br/><code>F12.6</code> | <code>%12.6f</code>',
 "Label: J' for upper state<br/>Description: Total rotational quantum number, excluding nuclear spin<br/>Fortran format | C format<br/><code>I7</code> | <code>%7d</code>",
 'Label: J" for lower state<br/>Description: Total rotational quantum number, excluding nuclear spin<br/>Fortran format | C format<br/><code>I7</code> | <code>%7d</code>',
 "Label: +/-' for upper state<br/>Description: Parity<br/>Fortran format | C format<br/><code>A1</code> | <code>%1s</code>",
 'Label: +/-" for lower state<br/>Description: Parity<br/>Fortran format | C format<br/><code>A1</code> | <code>%1s</code>',
 "Label: e/f' for upper state<br/>Description: Rotationless-parity<br/>Fortran format | C format<br/><code>A1</code> | <code>%1s</code>",
 'Label: e/f" for lower state<br/>Description: Rotationless-parity<br/>Fortran format | C format<br/><code>A1</code> | <code>%1s</code>',
 "Label: ElecState' for upper state<br/>Description: Electronic state<br/>Fortran format | C format<br/><code>A12</code> | <code>%12s</code>",
 'Label: ElecState" for lower state<br/>Description: Electronic state<br/>Fortran format | C format<br/><code>A12</code> | <code>%12s</code>',
 "Label: v' for upper state<br/>Description: State vibrational quantum number<br/>Fortran format | C format<br/><code>I3</code> | <code>%3d</code>",
 'Label: v" for lower state<br/>Description: State vibrational quantum number<br/>Fortran format | C format<br/><code>I3</code> | <code>%3d</code>',
 "Label: Λ' for upper state<br/>Description: Projection of the electronic angular momentum<br/>Fortran format | C format<br/><code>I3</code> | <code>%3d</code>",
 'Label: Λ" for lower state<br/>Description: Projection of the electronic angular momentum<br/>Fortran format | C format<br/><code>I3</code> | <code>%3d</code>',
 "Label: Σ' for upper state<br/>Description: Projection of the electronic spin<br/>Fortran format | C format<br/><code>I5</code> | <code>%5d</code>",
 'Label: Σ" for lower state<br/>Description: Projection of the electronic spin<br/>Fortran format | C format<br/><code>I5</code> | <code>%5d</code>',
 "Label: Ω' for upper state<br/>Description: Projection of the total angular momentum, Omega = Lambda + Sigma<br/>Fortran format | C format<br/><code>I5</code> | <code>%5d</code>",
 'Label: Ω" for lower state<br/>Description: Projection of the total angular momentum, Omega = Lambda + Sigma<br/>Fortran format | C format<br/><code>I5</code> | <code>%5d</code>']

In [161]:
header_names

['Frequency',
 'Uncertainty',
 'A',
 'E"',
 "g'",
 'g"',
 "J'",
 'J"',
 "+/-'",
 "e/f'",
 "ElecState'",
 "v'",
 "Λ'",
 "Σ'",
 "Ω'",
 '+/-"',
 'e/f"',
 'ElecState"',
 'v"',
 'Λ"',
 'Σ"',
 'Ω"']

In [140]:
head_tips = (header_details_df['labelname'].astype(str) + '<br/>' + 
             header_details_df['desc'].astype(str) + '<br/>' + 
             header_details_df['fmt'].astype(str)).tolist()
a = 'r' + head_tips[0]
a

'rLabel: E" for lower state<br/>Description: State energy in cm<sup>-1</sup><br/>Fortran format | C format<br/><code>F12.6</code> | <code>%12.6f</code>'

In [139]:
head_tips.tolist()

['Label: E" for lower state<br/>Description: State energy in cm<sup>-1</sup><br/>Fortran format | C format<br/><code>F12.6</code> | <code>%12.6f</code>',
 "Label: J' for upper state<br/>Description: Total rotational quantum number, excluding nuclear spin<br/>Fortran format | C format<br/><code>I7</code> | <code>%7d</code>",
 'Label: J" for lower state<br/>Description: Total rotational quantum number, excluding nuclear spin<br/>Fortran format | C format<br/><code>I7</code> | <code>%7d</code>',
 "Label: +/-' for upper state<br/>Description: Parity<br/>Fortran format | C format<br/><code>A1</code> | <code>%1s</code>",
 'Label: +/-" for lower state<br/>Description: Parity<br/>Fortran format | C format<br/><code>A1</code> | <code>%1s</code>',
 "Label: e/f' for upper state<br/>Description: Rotationless-parity<br/>Fortran format | C format<br/><code>A1</code> | <code>%1s</code>",
 'Label: e/f" for lower state<br/>Description: Rotationless-parity<br/>Fortran format | C format<br/><code>A1</code> | <code>%1s</code>',
 "Label: ElecState' for upper state<br/>Description: Electronic state<br/>Fortran format | C format<br/><code>A12</code> | <code>%12s</code>",
 'Label: ElecState" for lower state<br/>Description: Electronic state<br/>Fortran format | C format<br/><code>A12</code> | <code>%12s</code>',
 "Label: v' for upper state<br/>Description: State vibrational quantum number<br/>Fortran format | C format<br/><code>I3</code> | <code>%3d</code>",
 'Label: v" for lower state<br/>Description: State vibrational quantum number<br/>Fortran format | C format<br/><code>I3</code> | <code>%3d</code>',
 "Label: Λ' for upper state<br/>Description: Projection of the electronic angular momentum<br/>Fortran format | C format<br/><code>I3</code> | <code>%3d</code>",
 'Label: Λ" for lower state<br/>Description: Projection of the electronic angular momentum<br/>Fortran format | C format<br/><code>I3</code> | <code>%3d</code>',
 "Label: Σ' for upper state<br/>Description: Projection of the electronic spin<br/>Fortran format | C format<br/><code>I5</code> | <code>%5d</code>",
 'Label: Σ" for lower state<br/>Description: Projection of the electronic spin<br/>Fortran format | C format<br/><code>I5</code> | <code>%5d</code>',
 "Label: Ω' for upper state<br/>Description: Projection of the total angular momentum, Omega = Lambda + Sigma<br/>Fortran format | C format<br/><code>I5</code> | <code>%5d</code>",
 'Label: Ω" for lower state<br/>Description: Projection of the total angular momentum, Omega = Lambda + Sigma<br/>Fortran format | C format<br/><code>I5</code> | <code>%5d</code>']

In [122]:
header_tips = header_details_df['labelname'].tolist()
header_names

['Label: E" for lower state',
 "Label: J' for upper state",
 'Label: J" for lower state',
 "Label: +/-' for upper state",
 'Label: +/-" for lower state',
 "Label: e/f' for upper state",
 'Label: e/f" for lower state',
 "Label: ElecState' for upper state",
 'Label: ElecState" for lower state',
 "Label: v' for upper state",
 'Label: v" for lower state',
 "Label: Λ' for upper state",
 'Label: Λ" for lower state',
 "Label: Σ' for upper state",
 'Label: Σ" for lower state',
 "Label: Ω' for upper state",
 'Label: Ω" for lower state']

In [115]:
def get_tip(header_name):
    if header_name == 'Frequency':
        header_tip = r"Wavenumber in cm<sup>-1</sup><br/><code>F12.6</code> | <code>12.6%</code>"
    else:
        header_tip = "You're on your own"
    return header_tip

header_names = [col.replace('Sigma','Σ').replace('Lambda','Λ').replace('Omega','Ω') for col in csv_df.columns]
header_tips = [get_tip(header_name) for header_name in header_names]

zip(header_names, header_tips)

In [117]:
header_names, header_tips

(['Frequency',
  'Uncertainty',
  'A',
  'E"',
  "g'",
  'g"',
  "J'",
  'J"',
  "+/-'",
  "e/f'",
  "ElecState'",
  "v'",
  "Λ'",
  "Σ'",
  "Ω'",
  '+/-"',
  'e/f"',
  'ElecState"',
  'v"',
  'Λ"',
  'Σ"',
  'Ω"'],
 ['Wavenumber in cm<sup>-1</sup><br/><code>F12.6</code> | <code>12.6%</code>',
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own",
  "You're on your own"])

In [ ]:
def_json_df = pd.read_json(def_json_path, orient='columns')
states_col_dict = def_json_df['dataset']['states']['states_file_fields']
states_col_df = pd.DataFrame(states_col_dict).drop(columns='desc')
states_col_df['column'] = [item.replace('gtot','g').split(':')[-1] for item in states_col_df['name']]
states_col_df['case label'] = [item.split(':')[0] for item in states_col_df['name']]
states_col_df = states_col_df[~states_col_df['case label'].isin(['TROVE','Auxiliary'])]
states_col_df = states_col_df[~states_col_df['column'].isin(['Ja','tau','gfactor'])]
col_index = states_col_df.index
states_main_col = list(states_col_df['column'].values[:5])
J_fmt = states_col_df['cfmt'].values[3]
states_qn_label = list(states_col_df['column'].values[5:])
states_qn_format = list(states_col_df['cfmt'].values[5:])
states_colname = states_main_col+states_qn_label